include:
  - project: 'netconomy/cxbuild/build-templates'
    ref: v0.1.0
    file:
      - 'triggers.yml'
  - project: 'netconomy/spqx-tools/linter-templates'
    ref: 0.2.0
    file:
#      - 'markup/markdownlint.gitlab-ci.yml'
      - 'sourcecode/golang-ci-lint.gitlab-ci.yml'

image: golang:1.18-alpine

.build:
  stage: build
  before_script:
    - apk add --no-cache git
  script:
    - go build

.test:
  stage: test
  before_script:
    - apk add --no-cache make git
  script:
    - make test

build:ci:
  extends:
    - .build
    - .trigger-longliving
build:mr:
  extends:
    - .build
    - .trigger-mergerequest

test:ci:
  extends:
    - .test
    - .trigger-longliving
test:mr:
  extends:
    - .test
    - .trigger-mergerequest

_lint:golang-ci-lint:
  allow_failure: true

.deploy:
  stage: deploy
  image:
    name: docker:latest
  services:
    - docker:dind
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    GORELEASER_ARGS: ''

  script: |
    echo $PWD
    # GITLAB_TOKEN is needed to create GitLab releases.
    # DOCKER_* are needed to push Docker images.
    docker run --rm --privileged \
      -v $PWD:/go/src/net.netconomy/spqx-tools/container-juggler \
      -w /go/src/net.netconomy/spqx-tools/container-juggler \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e GITLAB_TOKEN=$GITLAB_TOKEN \
      goreleaser/goreleaser release --rm-dist $GORELEASER_ARGS

deploy_tag:
  extends:
    - .deploy
  only:
    - tags

deploy_branch:
  extends:
    - .deploy
  variables:
    GORELEASER_ARGS: '--snapshot'
  allow_failure: true
  only:
    - master
    - develop
  artifacts:
    paths:
      - dist
