before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - "-mod=mod"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
gitlab_urls:
  use_package_registry: true
release:
  gitlab:
    name: 34007531
  name_template: "container-juggler-v{{.Version}} {{.Env.USER}}"
